"""Some constants used by ttn application."""
import os


TTN_FOLDER_NAME = '.ttn'
TTN_CONFIG_DIR = f'{os.path.expanduser("~")}/{TTN_FOLDER_NAME}'
PROJECT_NAME_KEY = 'PROJECT_NAME'
PROJECT_SRC_DIR_KEY = 'PROJECT_SRC_DIR'
PROJECT_CLANG_INIT_PARAMS_KEY = 'PROJECT_CLANG_INIT_PARAMS'
PROJECT_CLANG_LOCK_KEY = 'PROJECT_CLANG_LOCK'
PROJECT_ARCH_NAME = 'PROJECT_ARCH_NAME'
PROJECT_ARCH_TIMINGS_PATH_KEY = 'PROJECT_ARCH_TIMINGS_PATH'
BBL_COUNTER_KEY = 'BBL_Counter'
LOOP_COUNTER_KEY = 'Loop_Counter'

INS_CACHE_SIZE_KEY = 'INS_CACHE_SIZE_KB'
INS_CACHE_LINES_KEY = 'INS_CACHE_LINES'
INS_CACHE_TYPE_KEY = 'INS_CACHE_TYPE'
INS_CACHE_MISS_CYCLES_KEY = 'INS_CACHE_MISS_CYCLES'

DATA_CACHE_SIZE_KEY = 'DATA_CACHE_SIZE_KB'
DATA_CACHE_LINES_KEY = 'DATA_CACHE_LINES'
DATA_CACHE_TYPE_KEY = 'DATA_CACHE_TYPE'
DATA_CACHE_MISS_CYCLES_KEY = 'DATA_CACHE_MISS_CYCLES'

CPU_CYCLE_NS_KEY = 'CPU_CYCLES_NS'

DEFAULT_PROJECT_NAME = 'DEFAULT'
DEFAULT_PROJECT_ARCH = 'Skylake'
DEFAULT_PROJECT_SRC_DIR = '/tmp'
DEFAULT_INS_CACHE_SIZE_KB = 32
DEFAULT_INS_CACHE_LINES = 32
DEFAULT_INS_CACHE_TYPE = 'DMA'
DEFAULT_INS_CACHE_MISS_CYCLES = 100
DEFAULT_DATA_CACHE_SIZE_KB = 32
DEFAULT_DATA_CACHE_LINES = 32
DEFAULT_DATA_CACHE_TYPE = 'DMA'
DEFAULT_DATA_CACHE_MISS_CYCLES = 100

NO_ARCH = 'ARCH_NONE'