"""Some constants used by ttn application."""
import os


TTN_FOLDER_NAME = '.ttn'
TTN_CONFIG_DIR = f'{os.path.expanduser("~")}/{TTN_FOLDER_NAME}'
PROJECT_NAME_KEY = 'PROJECT_NAME'
PROJECT_SRC_DIR_KEY = 'PROJECT_SRC_DIR'
PROJECT_CLANG_INIT_PARAMS_KEY = 'PROJECT_CLANG_INIT_PARAMS'
PROJECT_CLANG_LOCK_KEY = 'PROJECT_CLANG_LOCK'
PROJECT_ARCH_NAME = 'PROJECT_ARCH_NAME'
PROJECT_ARCH_TIMINGS_PATH_KEY = 'PROJECT_ARCH_TIMINGS_PATH'
BBL_COUNTER_KEY = 'BBL_Counter'
LOOP_COUNTER_KEY = 'Loop_Counter'

NIC_SPEED_MBPS_KEY = 'NIC_SPEED_MBPS'
CPU_CYCLE_NS_KEY = 'CPU_CYCLES_NS'
ROB_SIZE_KEY = 'ROB_SIZE'
DISPATCH_UNITS_KEY = 'DISPATCH_UNITS'
TIMING_MODEL_KEY = 'TIMING_MODEL'

# TODO: For now we only support one level of cache modelling i.e L1 cache
L1_INS_CACHE_SIZE_KEY = 'L1_INS_CACHE_SIZE_KB'
L1_INS_CACHE_LINES_SIZE_KEY = 'L1_INS_CACHE_LINE_SIZE'
L1_INS_CACHE_REPLACEMENT_POLICY_KEY = 'L1_INS_CACHE_REPLACEMENT_POLICY'
L1_INS_CACHE_MISS_CYCLES_KEY = 'L1_INS_CACHE_MISS_CYCLES'
L1_INS_CACHE_ASSOCIATIVITY_KEY = 'L1_INS_CACHE_ASSOCIATIVITY'

L1_DATA_CACHE_SIZE_KEY = 'L1_DATA_CACHE_SIZE_KB'
L1_DATA_CACHE_LINES_SIZE_KEY = 'L1_DATA_CACHE_LINE_SIZE'
L1_DATA_CACHE_REPLACEMENT_POLICY_KEY = 'L1_DATA_CACHE_REPLACEMENT_POLICY'
L1_DATA_CACHE_MISS_CYCLES_KEY = 'L1_DATA_CACHE_MISS_CYCLES'
L1_DATA_CACHE_ASSOCIATIVITY_KEY = 'L1_DATA_CACHE_ASSOCIATIVITY'


DEFAULT_PROJECT_NAME = 'DEFAULT'
DEFAULT_PROJECT_ARCH = 'NONE'
DEFAULT_PROJECT_SRC_DIR = '/tmp'
DEFAULT_NIC_SPEED_MBPS = 1000

# TODO: For now we only support one level of cache modelling i.e L1 cache
# Associativity = 1 <=> Direct-Mapped cache
DEFAULT_L1_INS_CACHE_ASSOCIATIVITY = 8
DEFAULT_L1_INS_CACHE_SIZE_KB = 32
DEFAULT_L1_INS_CACHE_LINE_SIZE_BYTES = 64
DEFAULT_L1_INS_CACHE_REPLACEMENT_POLICY = 'LRU'
DEFAULT_L1_INS_CACHE_MISS_CYCLES = 100

# Associativity = 1 <=> Direct-Mapped cache
DEFAULT_L1_DATA_CACHE_ASSOCIATIVITY = 8
DEFAULT_L1_DATA_CACHE_SIZE_KB = 32
DEFAULT_L1_DATA_CACHE_LINE_SIZE_BYTES = 64
DEFAULT_L1_DATA_CACHE_REPLACEMENT_POLICY = 'LRU'
DEFAULT_L1_DATA_CACHE_MISS_CYCLES = 100


DEFAULT_ROB_SIZE = 1024
DEFAULT_NUM_DISPATCH_UNITS = 8
DEFAULT_TIMING_MODEL = 'EMPIRICAL'

NO_ARCH = 'ARCH_NONE'
