#ifndef __VT_DEFINITIONS__
#define __VT_DEFINITIONS__

#define VT_IOC_MAGIC 'k'

#define VT_UPDATE_TRACER_CLOCK _IOW(VT_IOC_MAGIC, 1, int)
#define VT_WRITE_RESULTS _IOW(VT_IOC_MAGIC, 2, int)
#define VT_GET_CURRENT_VIRTUAL_TIME _IOW(VT_IOC_MAGIC, 3, int)
#define VT_REGISTER_TRACER _IOW(VT_IOC_MAGIC, 4, int)
#define VT_ADD_PROCESSES_TO_SQ _IOW(VT_IOC_MAGIC, 5, int)
#define VT_SYNC_AND_FREEZE _IOW(VT_IOC_MAGIC, 6, int)
#define VT_INITIALIZE_EXP _IOW(VT_IOC_MAGIC, 7, int)
#define VT_GETTIME_TRACER _IOW(VT_IOC_MAGIC, 8, int)
#define VT_STOP_EXP _IOW(VT_IOC_MAGIC, 9, int)
#define VT_PROGRESS_BY _IOW(VT_IOC_MAGIC, 10, int)
#define VT_PROGRESS_TIMELINE_BY _IOW(VT_IOC_MAGIC, 11, int)
#define VT_WAIT_FOR_EXIT _IOW(VT_IOC_MAGIC, 12, int)
#define VT_SLEEP_FOR _IOW(VT_IOC_MAGIC, 13, int)
#define VT_RELEASE_WORKER _IOW(VT_IOC_MAGIC, 14, int)
#define VT_SET_RUNNABLE _IOW(VT_IOC_MAGIC, 15, int)
#define VT_GETTIME_MY_PID _IOW(VT_IOC_MAGIC, 16, int)
#define VT_ADD_TO_SQ _IOW(VT_IOC_MAGIC, 17, int)
#define VT_SYSCALL_WAIT _IOW(VT_IOC_MAGIC, 18, int)
#define VT_GETTIME_PID _IOW(VT_IOC_MAGIC, 19, int)
#define VT_SET_PACKET_SEND_TIME _IOW(VT_IOC_MAGIC, 20, int)
#define VT_GET_PACKET_SEND_TIME _IOW(VT_IOC_MAGIC, 21, int)
#define VT_GET_NUM_ENQUEUED_BYTES _IOW(VT_IOC_MAGIC, 22, int)
#define VT_SET_EAT _IOW(VT_IOC_MAGIC, 23, int)
#define VT_GET_EAT _IOW(VT_IOC_MAGIC, 24, int)
#define VT_SET_PROCESS_LOOKAHEAD _IOW(VT_IOC_MAGIC, 25, int)
#define VT_GET_TRACER_LOOKAHEAD _IOW(VT_IOC_MAGIC, 26, int)
#define VT_GET_TRACER_NEAT_LOOKAHEAD _IOW(VT_IOC_MAGIC, 27, int)

#define VT_WRITE_RES 'b'

#endif
